export { BaseApiClient } from './baseApiClient';
export { teacherApiClient } from './teacherApi';
export { authApiClient } from './authApi';
export { gradeApiClient } from './gradeApi';
export { subjectApiClient } from './subjectApi';
export { scheduleApiClient } from './scheduleApi';
export { classApiClient } from './classApi';
export { consultationApiClient } from './consultationApi';
export { newsApiClient } from './newsApi';